pool:
  vmImage: 'ubuntu-16.04'

steps:
- task: NodeTool@0 
  inputs:
    versionSpec: '8.11.1' 
- script: npm install
- script: npm test --ci --reporters=default --reporters=jest-junit
- task: PublishTestResults@2
  inputs:
    testRunner: JUnit
    testResultsFiles: ./test-results.xml
